name: Build

on:
    push:
        branches: [master, feature/actions]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: package-setup
              run: |
                sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
                # sudo apt-get install libvulkan-dev vulkan-utils
                sudo apt-get install ninja-build
            - name: vulkan-sdk
              run: |
                wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
                sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.148-bionic.list https://packages.lunarg.com/vulkan/1.2.148/lunarg-vulkan-1.2.148-bionic.list
                sudo apt update
                sudo apt install vulkan-sdk
            - name: post
              run: vulkaninfo
            - name: bootstrap
              run: sh bootstrap
            - name: build-all
              run: ninja demos
            - name: upload
              uses: actions/upload-artifact@v2
              with:
                name: libtxtquad
                path: bin/libtxtquad.so
