name: Build

on:
    push:
        branches: [master, feature/actions]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: package-setup
              run: |
                sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
                sudo apt-get install libvulkan-dev vulkan-utils
                sudo apt-get install ninja-build
            - name: bootstrap
              run: sh bootstrap
            - name: build-all
              run: ninja demos
